
tasks:
  - name: NPM Server
    init: npm install && npm run build
    command: npm run dev
  - name: git
    init: echo "Terminál pro práci s gitem"
    
ports:
  - port: 3000
    onOpen: open-preview
    



vscode:
  extensions:
    - eamodio.gitlens